apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  destination:
    server: https://F0F4C112F815640983D2390F143D43A0.sk1.us-east-2.eks.amazonaws.com
    namespace: observability
  source:
    repoURL: https://github.com/bfbarkhouse/redpanda-connect-gitops
    targetRevision: main
    path: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
