{
 "title": "Redpanda Connect",
 "description": "Dashboard for Redpanda Connect",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Input connections up",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(input_connection_up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output connections up",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(output_connection_up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Input connections failed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(input_connection_failed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output connections failed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(output_connection_failed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Input connections lost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(input_connection_lost)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output connections lost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(output_connection_lost)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output errors",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(output_error)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total batch created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "per minute" } },
   "targets": [
    {
     "expr": "sum(rate(batch_created[5m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "per minute" } },
   "targets": [
    { "expr": "rate(output_sent[5m])*60", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Input latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "input_latency_ns{quantile=\"0.5\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Output latency sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "output_latency_ns{quantile=\"0.5\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Processor Batch Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "per minute" } },
   "targets": [
    {
     "expr": "rate(processor_batch_received[5m])*60",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Processor Batch Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "per minute" } },
   "targets": [
    {
     "expr": "rate(processor_batch_sent[5m])*60",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Processor Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "processor_error", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Processor Latency ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "processor_latency_ns", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Processor Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "per minute" } },
   "targets": [
    {
     "expr": "rate(processor_received[5m])*60",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Processor Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "per minute" } },
   "targets": [
    { "expr": "rate(processor_sent[5m])*60", "legendFormat": "{{path}}" }
   ]
  }
 ]
}